# Generated by Django 4.2 on 2023-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_anonymizer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="address",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="address",
            name="portal_code",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(default="", max_length=128),
        ),
    ]
