# Generated by Django 4.2 on 2023-04-21 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_anonymizer", "0002_address_city_address_contact_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="portal_code",
            new_name="postal_code",
        ),
    ]
